---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "51"

  name: logs
spec:
  version: 8.10.2
  nodeSets:
  - name: default
    count: 2
    config:
      node.store.allow_mmap: false
