---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "52"

  name: logs
spec:
  version: 8.10.2
  count: 1
  elasticsearchRef:
    name: logs
  http:
    tls:
      selfSignedCertificate:
        disabled: true
