apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gp-rancher-monitoring
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io/foreground
spec:
  destination:
    namespace: cattle-monitoring-system
    server: {{ .Values.destination.cluster }}
  project: {{ .Values.destination.project }}
  source:
    path: charts/gp-rancher-monitoring
    repoURL: {{ .Values.source.gpRepoUrl }}
    targetRevision: {{ .Values.source.revision }}
    helm:
      valueFiles:
      - profiles/{{ .Values.gpRancherMonitoring.profile }}.yaml

      values: {{ .Values.gpRancherMonitoring.customValues | quote }}
  syncPolicy: {}