#Minimal configuration of a cluster with version 2.X of the operator.
#Note the replacement of 'master' role with 'cluster_manager' on line 49
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: opensearch-logs
spec:
  security:
    config:
    tls:
       http:
         generate: true
       transport:
         generate: true
         perNode: true
  general:
    setVMMaxMapCount: true
    httpPort: 9200
    serviceName: opensearch-logs
    version: 2.11.0
    pluginsList: ["repository-s3"]
    drainDataNodes: true
  dashboards:
    tls:
      enable: false
      generate: true
    version: 2.11.0
    enable: true
    replicas: 1
    resources:
      requests:
         memory: "512Mi"
         cpu: "200m"
      limits:
         memory: "512Mi"
         cpu: "200m"
    additionalConfig:
      opensearch_security.multitenancy.enabled: "true"
      plugins.query.datasources.encryption.masterkey: "abf961f3bef08f8e5bff4533"
  nodePools:
    - component: masters
      replicas: 3
      diskSize: "20Gi"
      resources:
         requests:
            memory: "4Gi"
            cpu: "1"
         limits:
            memory: "4Gi"
            cpu: "1"
      roles:
        - "data"
        - "cluster_manager"
        - "ingest"
