---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.syncWave | quote }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      #affinity:
      #  podAntiAffinity:
      #    preferredDuringSchedulingIgnoredDuringExecution:
      #    - podAffinityTerm:
      #        labelSelector:
      #          matchExpressions:
      #          - key: name
      #            operator: In
      #            values:
      #            - pgcheck
      #        topologyKey: kubernetes.io/hostname
      #      weight: 1
      containers:
      - image: bernhard97/webservice:0.1.3
        imagePullPolicy: IfNotPresent
        #imagePullPolicy: Always
        name: webservice
        command: ["./run.rb"]
        env:
        - name: SECRET
          value: "{{ .Values.secret }}"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: PORT
          value: "8080"

        ports:
          - name: web
            containerPort: 8080

        livenessProbe:
          httpGet:
            port: web
            path: healthz/alive
          initialDelaySeconds: 40
          periodSeconds: 15

        readinessProbe:
          httpGet:
            port: web
            path: healthz/ready
          periodSeconds: 5
          initialDelaySeconds: 60

        resources:
          requests:
            memory: 64Mi
            cpu: 500m
          limits:
            memory: 64Mi
            cpu: 500m
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: true
      restartPolicy: Always

