---
apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
  name: "webservice-logs"
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
spec:
  filters:
  - record_modifier:
      records:
      - logindex: "ns-${record['kubernetes']['namespace_name']}"
  globalOutputRefs:
    - "opensearch"
