rancher-logging:
  images:
    fluentd:
      repository: ghcr.io/kube-logging/fluentd
      tag: v1.15.3
  loggingOverlay:
    spec:
      defaultFlow:
        filters:
        - record_modifier:
            records:
            - logindex: "system"
        globalOutputRefs:
        - "opensearch"

logDestination: opensearch
