rancher-logging:
  loggingOverlay:
    spec:
      defaultFlow:
        filters:
        - record_modifier:
            records:
            - logindex: "system"
        globalOutputRefs:
        - "opensearch"

logDestination: opensearch
