---
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: "elastic-search"
  namespace: "cattle-logging-system"
spec:
  elasticsearch:
    host: logs-es-http
    port: 9200
    scheme: https
    ssl_verify: false
    user: elastic
    password:
      valueFrom:
        secretKeyRef:
          name: logs-es-elastic-user
          key: elastic

    logstash_format: true
    include_timestamp: true

    logstash_prefix: "logs_${logindex}"

    log_es_400_reason: true

    buffer:
      flush_mode: "interval"
      flush_interval: "20s"



