# Default values for all apps

destination:
  cluster: https://kubernetes.default.svc
  project: default

source:
  gpRepoUrl: https://github.com/BernhardDenner/gp-poc.git
  revision: HEAD

gpRancherMonitoring:
  profile: small
  customValues: ""