# Default values for all apps

destination:
  cluster: https://kubernetes.default.svc
  project: default

source:
  gpRepoUrl: https://github.com/BernhardDenner/gp-poc.git
  revision: HEAD

# global values

# cluster system_domain used to define all paas and daas service
# ingress routes
# e.g. - grafana.<system_domain>
#system_domain: example.com

modules:
  elastic:
    enabled: false
  opensearch:
    enabled: true
  cloudnativepg:
    enabled: true

gpRancherMonitoring:
  profile: small
  customValues: ""
